language: python
cache:
  directories:
    - local
    - repo
install:
  - pip install ocrd
  - make build-olena
  - export PATH="$PWD/local/bin:$PATH"
script:
  - make assets test OCRD_BASEURL="https://github.com/OCR-D/ocrd-assets/raw/master/data/"
