language: python
cache:
  directories:
    - local
install:
  - sudo apt update
  - sudo make deps-ubuntu
  - make deps
  - export PATH="$PWD/local/bin:$PATH"
script:
  - make test OCRD_BASEURL="https://github.com/OCR-D/assets/raw/master/data/"
