language: python
cache:
  directories:
    - local
    - repo
install:
  - sudo apt update
  - sudo make deps-ubuntu
  - make deps
  - export PATH="$PWD/local/bin:$PATH"
script:
  - make assets test OCRD_BASEURL="https://github.com/OCR-D/ocrd-assets/raw/master/data/"
