#!/bin/bash

SHAREDIR=$(cd $(dirname $0);pwd)

main () {
    source `ocrd bashlib filename`
    ocrd__wrap "$SHAREDIR/ocrd-tool.json" "ocrd-olena-sauvola" "$@"

    ocrd workspace -d "${argv[workdir]}" find -a -G "${argv[input_file_grp]}" -k "local_filename"
    # |while read -r infile;do
    #     echo "$infile"
    # done
    
    # scribo-cli sauvola 

    # workdir=`ocrd workspace clone -m "${argv[mets_file]}"`
    # echo "WORKDIR IS $workdir"
    # ALTO=`ocrd workspace -d "$workdir" find -al -G OCR-D-GT-ALTO`
    # PAGE=`ocrd workspace -d "$workdir" find -al -G OCR-D-GT-PAGE`
    # run -gt "$PAGE" -ocr "$PAGE" -d "$workdir"
}


main "$@"
