version: 2.1
jobs:

  build-olena:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker      # https://circleci.com/docs/2.0/building-docker-images/
      - run: make deps-ubuntu
      - run: apt-get install imagemagick
      - run: make build-olena
      - run: make test
      - run: make docker

workflows:
  version: 2
  build-master:
    jobs:
      - build-olena
