version: 2.1
jobs:

  build-olena:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker      # https://circleci.com/docs/2.0/building-docker-images/
      - run: sudo make deps-ubuntu
      - run: sudo apt-get install imagemagick python3-pip
      - run: make build-olena
      - run: sudo make install PREFIX=/usr/local
      - run: make test
      - run: make docker
      - run: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push ocrd/olena:latest
      - run: docker push ocrd/olena:build-olena

workflows:
  version: 2
  build-master:
    jobs:
      - build-olena
