version: 2.1
jobs:

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: git config --global --add safe.directory '*'
      - run: sudo git config --global --add safe.directory '*'
      - run: sudo apt-get update
      - run: sudo apt-get install imagemagick python3-pip ca-certificates g++ make automake libtool pkgconf
      - run: sudo make deps-ubuntu
      - run: make build-olena PREFIX=/usr/local
      - run: make deps
      - run: sudo make install
      - run: make test
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker # https://circleci.com/docs/2.0/building-docker-images/
      - run: make docker
    resource_class: large

  deploy-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker # https://circleci.com/docs/2.0/building-docker-images/
      - run:
          name: Login to Dockerhub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build OCR-D image
          command: make docker && docker push ocrd/olena:latest
      - run:
          name: Build Olena image
          environment:
            DOCKER_STAGE: olena
            DOCKER_TAG: ocrd/olena:build-olena
          command: make docker && docker push $DOCKER_TAG

workflows:
  version: 2
  build-master:
    jobs:
      - deploy-docker:
          filters:
            branches:
              only: master
  test-pull-request:
    jobs:
      - test
      - build-docker
